# Generated by Django 4.2.1 on 2023-05-04 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptos', '0001_initial'),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookmarkModel',
            new_name='Bookmark',
        ),
    ]
