# Generated by Django 4.2.1 on 2023-05-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0002_alter_crypto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='ids',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='symbol',
            field=models.CharField(max_length=500),
        ),
    ]
