# Generated by Django 4.2.1 on 2023-05-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0003_alter_crypto_ids_alter_crypto_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
